#include <iostream>
using namespace std;


int main(){
   // int n;
   // cin>>n;

    //n==5

   /* for(int i=1;i<=100;i++){
            cout << i << endl;
        if(i==n)
            break;
    } */

   /* for(int i=1;i<=5;i++){
        for(int j=1;j<=5;j++){
            if(j==3)
                break;
            cout << j << " ";
        }
        //////move to this point
        cout << endl;
    } */

   /* for(int i=1;i<=10;i++){
        if(i==4)
            continue;
        cout << i << " ";  //ye exceute nhi hoga for i==4

    } */

    int i=1;
    while(i<10){
            cout << i << endl;
             i++;
        if(i==4)
            continue;
         i++;
    }






}



