#include <iostream>
using namespace std;


int main(){
   /* char c;
    cin>>c;

    if(c>='a' && c<='z')
        cout << "Lower Case" << endl;
   else if(c>='A' && c<='Z')
    cout << "Upper Case" << endl;
    else
        cout << "Invalid Input";

    if(0)   //non-zero means true ,zero means false;
        cout << "Hello " << endl; */
    bool c=0;
    if(c==true)
        cout << "It is true" << endl;
    else
        cout << "It is false" << endl;

}
