#include <iostream>
using namespace std;


int main(){
      // int n;
      // cin>>n;
     //int arr[];
     int arr[]={1,2,3,4,5,6,7,8,9,10,11};
     cout << sizeof(arr)/sizeof(arr[5]) << endl;
       //elements are also given
     //for intialising rest of the elements with 0,atleast give one value
   /* for(int i=5;i<10;i++){
        cin>>arr[i];
    } */

   /* for(int i=n-1;i>=0;i--){
        cout << arr[i] << " ";
    } */

}
